<!doctype html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <link href="<?=$this->baseUrl('css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css">
        <link href="<?=$this->baseUrl('css/bootstrap-theme.min.css') ?>" rel="stylesheet" type="text/css">
        <style>
            body {
                padding-top: 70px;
            }
        </style>
    </head>
    <body>
        <a href="#content" class="sr-only">Skip to content</a>

        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->baseUrl('') ?>">Wimta Framework</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="<?=$this->baseUrl('') ?>">Главная</a></li>
                        <li><a href="<?= $this->baseUrl('quick-start') ?>">Быстрый старт</a></li>
                        <li><a href="<?= $this->baseUrl('structure') ?>">Структура</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                API
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?= $this->baseUrl('api') ?>#helpers">Конфигурация</a></li>
                                <li><a href="<?= $this->baseUrl('api') ?>#helpers">Хелперы</a></li>
                                <li><a href="<?= $this->baseUrl('api') ?>#library">Библиотека</a></li>
                            </ul>
                        </li>
                        <li><a href="<?=$this->baseUrl('articles') ?>">Блог</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a target="_blank" href="https://github.com/SazereS/WimtaFramework" title="GitHub">
                                <img
                                    src="<?=$this->baseUrl('images/glyphicons_social_21_github.png') ?>"
                                    class="img-responsive"
                                    />
                            </a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">
            <div id="content" class="row">
                <div class="col-md-12">
                    <?=$content ?>
                </div>
            </div>
        </div>
        <script src="//code.jquery.com/jquery.js"></script>
        <script src="<?=$this->baseUrl('js/bootstrap.min.js') ?>"></script>
    </body>
</html>