<div class="jumbotron">
    <div class="row">
        <div class="col-md-3">
            <img class="" src="<?=$this->baseUrl('images/cat_laptop.png') ?>" />
        </div>
        <div class="col-md-8 col-md-offset-1">
            <h1>Wimta Framework</h1>
            <p>Text with framework description</p>
            <p>
                <a class="btn btn-lg btn-primary" href="#">Free download &raquo;</a>
            </p>
        </div>
    </div>
</div>