<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>default</title>
    </head>
    <body>
    <div style="width:980px; margin:0 auto;">
    	<!--<div>
	    	<img src="<?=$this->baseUrl('wimta_logo.png'); ?>" style="width: 250px; float: left;" />
	    	<h1 style="font-family: Helvetica; font-size: 60px; margin:0 auto; padding-top: 80px; padding-left: 320px;">WIMTA Framework</h1>
    	</div>-->
    	<img src="<?=$this->baseUrl('wimta_logo_big.png'); ?>" style="width: 100%;" />
    	<div>
    		<?=$content ?>
		</div>
		<div style="position: fixed; bottom: 10px; width:980px;">
			<center><em><p><a href="https://github.com/SazereS/WimtaFramework/releases">On GitHub</a></p></em></center>
		</div>
    </div>
    	
    </body>
</html>