<form class="form-horizontal" role="form" method="POST">
    <div class="form-group">
        <label class="col-lg-2 control-label" for="input-title">Заголовок записи</label>
        <div class="col-lg-10">
            <input type="text" name="title" value="<?=$this->post['title'] ?>" class="form-control" id="input-title" placeholder="Заголовок записи">
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label" for="input-text">Текст записи</label>
        <div class="col-lg-10">
            <textarea name="text" rows="15" class="form-control" id="input-text" placeholder="Текст записи"><?=$this->post['text'] ?></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label"></label>
        <div class="col-lg-10">
            <button type="submit" class="btn btn-primary btn-lg">Сохранить</button>
        </div>
    </div>
</form>