<div class="jumbotron">
    <div class="row">
        <div class="col-md-3">
            <img src="<?= $this->baseUrl('images/cat_birdhouse.png') ?>" />
        </div>
        <div class="col-md-8 col-md-offset-1">
            <h1>Page 403</h1>
            <p>Упс! Не хватает привелегий для доступа к запрошенному ресурсу!</p>
            <p>
                <a class="btn btn-lg btn-primary" href="<?= $this->baseUrl('') ?>">На главную &raquo;</a>
            </p>
        </div>
    </div>
</div>